#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

awk -F: -v v="/home" '{if ($6~v) if ( -d $6 ) print "cp -rv /etc/skel/* "$6" && cp -rv /etc/skel/.[!.]* "$6" && chown "$1" "$6" -R" fi fi }' /etc/passwd | zsh
cp -rv /etc/skel/* /root && cp -rv /etc/skel/.[!.]* /root
