#!/bin/bash

set -e

if [[ "$1" = "configure" ]]; then

git clone https://github.com/ohmyzsh/ohmyzsh.git /etc/skel/.oh-my-zsh 2> /dev/null || true
git clone https://github.com/ohmyzsh/ohmyzsh.git /root/.oh-my-zsh 2> /dev/null || true
cp -f /usr/share/kaisen-skeleton/.zshrc /root || true
cp -rf /usr/share/kaisen-skeleton/.config /etc/skel || true
cp -f /usr/share/kaisen-skeleton/.face /etc/skel || true
cp -f /usr/share/kaisen-skeleton/.zshrc /etc/skel || true
cp -rf /usr/share/kaisen-skeleton/.local /etc/skel || true
cp -rf /usr/share/kaisen-skeleton/.kde /etc/skel || true
cp -f /usr/share/kaisen-skeleton/.gtkrc-2.0 /etc/skel || true
cp -rf /usr/share/kaisen-skeleton/Desktop /etc/skel || true
cp -f /usr/share/kaisen-skeleton/.conkyrc /etc/skel || true
cd /etc/skel
ln -s .face .face.icon 2> /dev/null || true
rm -rf /usr/share/kaisen-skeleton || true

fi

#DEBHELPER#
