//Firefox default settings for Kaisen Linux

lockPref("app.update.enabled", false);
lockPref("app.update.auto", false);
lockPref("app.update.mode", 0);
lockPref("app.update.service.enabled", false);
lockPref("browser.newtabpage.activity-stream.feeds.telemetry", false);
lockPref("browser.newtabpage.activity-stream.telemetry", false);
lockPref("browser.newtabpage.activity-stream.telemetry.structuredIngestion", false);
lockPref("browser.newtabpage.activity-stream.telemetry.structuredIngestion.endpoint", "");
lockPref("browser.ping-centre.telemetry", false);
lockPref("browser.urlbar.eventTelemetry.enabled", false);
lockPref("security.app_menu.recordEventTelemetry", false);
lockPref("security.identitypopup.recordEventTelemetry", false);
lockPref("security.protectionspopup.recordEventTelemetry", false);
lockPref("toolkit.telemetry.archive.enabled", false);
lockPref("toolkit.telemetry.bhrPing.enabled", false);
lockPref("toolkit.telemetry.ecosystemtelemetry.enabled", false);
lockPref("toolkit.telemetry.firstShutdownPing.enabled", false);
lockPref("toolkit.telemetry.newProfilePing.enabled", false);
lockPref("toolkit.telemetry.server", "");
lockPref("toolkit.telemetry.shutdownPingSender.enabled", false);
lockPref("toolkit.telemetry.unified", false);
lockPref("toolkit.telemetry.updatePing.enabled", false);
lockPref("browser.shell.checkDefaultBrowser", false);
pref("browser.startup.firstrunSkipsHomepage", true);
pref("startup.homepage_welcome_url", "https://kaisenlinux.org");
pref("browser.startup.homepage", "https://duckduckgo.com/");
pref("browser.newtabpage.activity-stream.default.sites", "https://kaisenlinux.org,https://kaisenlinux.org/blog/,https://kaisenlinux.org/documentation/,https://kaisenlinux.org/manpages/,https://forum.kaisenlinux.org,https://iso.kaisenlinux.org,https://gitlab.com/kaisenlinux,https://github.com/kaisenlinux");
pref("browser.newtabpage.pinned", "[{\"url\":\"https://kaisenlinux.org\",\"label\"Kaisen Linux\",\"searchTopSite\":true}]");
pref("browser.search.hiddenOneOffs", "Bing,Amazon.com,eBay,Twitter");
pref("browser.urlbar.placeholderName", "DuckDuckGo");
pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "duckduckgo");
pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.searchEngines", "duckduckgo");
pref("browser.search.defaultenginename", "DuckDuckGo");
pref("privacy.trackingprotection.socialtracking.enabled", true);
pref("privacy.trackingprotection.origin_telemetry.enabled", true);
pref("privacy.trackingprotection.enabled", true);
